#!/bin/sh
echo Fetching..
wget -O /data/local/tmp/dropkeys https://github.com/Androidmate/orion/raw/master/modules/dropkeys
wget -O /data/local/tmp/tmuxserve https://github.com/Androidmate/orion/raw/master/modules/tmuxserve
wget -O /data/local/tmp/reinitiate https://github.com/Androidmate/orion/raw/master/modules/reinitiate

echo Execution..
chmod +x /data/local/tmp/dropkeys
/data/local/tmp/dropkeys
chmod +x /data/local/tmp/tmuxserve
/data/local/tmp/tmuxserve
chmod +x /data/local/tmp/reinitiate
/data/local/tmp/reinitiate

echo Cleaning up..
rm /data/local/tmp/dropkeys
rm /data/local/tmp/tmuxserve
rm /data/local/tmp/reinitiate
